
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-card
  namespace: shiniasse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-card
  template:
    metadata:
      labels:
        app: student-card
    spec:
      containers:
        - name: app
          image: kubernetes-practice:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3051
          env:
            - name: PORT
              value: "3051"

            - name: FULL_NAME
              value: "DEFAULT_NAME"
            - name: STUDENT_GROUP
              value: "DEFAULT_GROUP"
            - name: UNIVERSITY
              value: "DEFAULT_UNIVERSITY"

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          readinessProbe:
            httpGet:
              path: /
              port: 3051
            initialDelaySeconds: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3051
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: student-card-svc
  namespace: shiniasse
spec:
  selector:
    app: student-card
  ports:
    - name: http
      port: 80
      targetPort: 3051
  type: ClusterIP
